stages:
  raw_train_test_split:
    cmd: python src/scripts/ts_preproc.py ${paths.raw} ${paths.preprocessed} ${paths.train_val_test} ${paths.scaler} ${model_parameters.lag_input} ${model_parameters.forecast_horizon}
    deps:
    - data/raw/train.csv
    - src/scripts/ts_preproc.py
    outs:
    - data/scalers/scaler.pkl
    - data/preprocessed/preprocessed.csv
    - data/interim/train_preprocessed.csv
    - data/interim/val_preprocessed.csv
    - data/interim/test_preprocessed.csv
  train:
    # cmd: python src/scripts/ts_train.py ${paths.train_val_test} /home/arazin/main/university/AMLT/params.yaml ${paths.prediction_path} # lstm
    cmd: python src/scripts/ts_arima_train.py ${paths.train_val_test} /home/arazin/main/university/AMLT/params.yaml ${paths.prediction_path} # arima
    deps:
    - data/interim/train_preprocessed.csv
    - data/interim/val_preprocessed.csv
    - data/interim/test_preprocessed.csv